import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useState, useRef } from "react";
import { detectImage, type DetectionResult } from "@/lib/detect.functions";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Upload, ScanEye, Loader2, ShieldCheck, ShieldAlert, Sparkles } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "TruthLens — AI Image Detection" },
      {
        name: "description",
        content:
          "Upload an image and TruthLens analyzes whether it was generated by AI or captured authentically.",
      },
      { property: "og:title", content: "TruthLens — AI Image Detection" },
      {
        property: "og:description",
        content: "Detect AI-generated images with forensic visual analysis.",
      },
    ],
  }),
  component: Index,
});

function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result));
    r.onerror = () => reject(r.error);
    r.readAsDataURL(file);
  });
}

function Index() {
  const detect = useServerFn(detectImage);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [loading, setLoading] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  async function handleFile(file: File) {
    if (!file.type.startsWith("image/")) {
      toast.error("Please upload an image file");
      return;
    }
    if (file.size > 8 * 1024 * 1024) {
      toast.error("Image must be under 8 MB");
      return;
    }
    setResult(null);
    setLoading(true);
    try {
      const dataUrl = await fileToDataUrl(file);
      setImageUrl(dataUrl);
      const res = await detect({ data: { imageDataUrl: dataUrl } });
      console.log("[TruthLens] Result:", res);
      setResult(res);
    } catch (e) {
      console.error(e);
      toast.error(e instanceof Error ? e.message : "Analysis failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/40">
      <header className="border-b border-border/60 bg-background/70 backdrop-blur">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2">
            <ScanEye className="h-6 w-6 text-primary" />
            <span className="text-lg font-semibold tracking-tight">TruthLens</span>
          </div>
          <Badge variant="secondary" className="gap-1">
            <Sparkles className="h-3 w-3" /> Powered by Lovable AI
          </Badge>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-6 py-12">
        <section className="text-center">
          <h1 className="text-balance text-4xl font-bold tracking-tight sm:text-5xl">
            Is this image real, or made by AI?
          </h1>
          <p className="mx-auto mt-3 max-w-2xl text-balance text-muted-foreground">
            Upload a photo and TruthLens performs a forensic visual analysis to
            estimate whether it was generated by an AI model or captured
            authentically.
          </p>
        </section>

        <div className="mt-10 grid gap-6 md:grid-cols-2">
          <Card
            className="flex min-h-[320px] flex-col items-center justify-center border-dashed p-6 text-center"
            onDragOver={(e) => e.preventDefault()}
            onDrop={(e) => {
              e.preventDefault();
              const f = e.dataTransfer.files?.[0];
              if (f) handleFile(f);
            }}
          >
            {imageUrl ? (
              <div className="w-full">
                <img
                  src={imageUrl}
                  alt="Uploaded for analysis"
                  className="mx-auto max-h-[320px] rounded-lg object-contain"
                />
                <Button
                  variant="outline"
                  className="mt-4"
                  onClick={() => fileRef.current?.click()}
                  disabled={loading}
                >
                  Upload a different image
                </Button>
              </div>
            ) : (
              <>
                <div className="rounded-full bg-primary/10 p-4">
                  <Upload className="h-7 w-7 text-primary" />
                </div>
                <h3 className="mt-4 font-semibold">Drop an image here</h3>
                <p className="mt-1 text-sm text-muted-foreground">
                  PNG, JPG, WebP — up to 8 MB
                </p>
                <Button
                  className="mt-4"
                  onClick={() => fileRef.current?.click()}
                  disabled={loading}
                >
                  Choose image
                </Button>
              </>
            )}
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={(e) => {
                const f = e.target.files?.[0];
                if (f) handleFile(f);
                e.target.value = "";
              }}
            />
          </Card>

          <Card className="min-h-[320px] p-6">
            {loading ? (
              <div className="flex h-full flex-col items-center justify-center text-center">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="mt-3 text-sm text-muted-foreground">
                  Analyzing image…
                </p>
              </div>
            ) : !result ? (
              <div className="flex h-full flex-col items-center justify-center text-center text-muted-foreground">
                <ScanEye className="h-8 w-8" />
                <p className="mt-3 text-sm">
                  Analysis results will appear here.
                </p>
              </div>
            ) : (
              <ResultView result={result} />
            )}
          </Card>
        </div>
      </main>
    </div>
  );
}

function ResultView({ result }: { result: DetectionResult }) {
  const isAi = result.classification === "Likely AI-generated";
  const isDemo = result.isDemo;

  return (
    <div className="flex h-full flex-col">
      <div className="flex items-center gap-3">
        {isDemo ? (
          <Sparkles className="h-7 w-7 text-muted-foreground" />
        ) : isAi ? (
          <ShieldAlert className="h-7 w-7 text-destructive" />
        ) : (
          <ShieldCheck className="h-7 w-7 text-emerald-500" />
        )}
        <div>
          <div className="text-xl font-semibold">{result.classification}</div>
          {!isDemo && (
            <div className="text-xs text-muted-foreground">
              Model confidence: {(result.confidence * 100).toFixed(1)}%
            </div>
          )}
        </div>
      </div>

      {!isDemo && (
        <div className="mt-5 space-y-4">
          <ProbRow label="AI-generated" value={result.aiProbability} tone="ai" />
          <ProbRow label="Authentic" value={result.realProbability} tone="real" />
        </div>
      )}

      {result.reasoning && (
        <p className="mt-5 text-sm leading-relaxed text-muted-foreground">
          {result.reasoning}
        </p>
      )}

      {result.signals.length > 0 && (
        <div className="mt-4">
          <div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Signals
          </div>
          <ul className="mt-2 flex flex-wrap gap-1.5">
            {result.signals.map((s, i) => (
              <li key={i}>
                <Badge variant="secondary" className="font-normal">
                  {s}
                </Badge>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

function ProbRow({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone: "ai" | "real";
}) {
  const pct = (value * 100).toFixed(1);
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-sm">
        <span className="font-medium">{label}</span>
        <span className="tabular-nums text-muted-foreground">{pct}%</span>
      </div>
      <Progress
        value={value * 100}
        className={tone === "ai" ? "[&>div]:bg-destructive" : "[&>div]:bg-emerald-500"}
      />
    </div>
  );
}
